### ISSUE TITLE
Omit images entry if no preview image found

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/page-metadata-service#57]
If the parser is unable to determine a preview image, it should return an empty array for images.

**Comment by pdehaan** [comment]
Do we have a screenshot service anywhere?
Like, if a preview image cannot be found, we call a worker which takes a screenshot of the specified URL and then uses that as the preview image?

I can see returning an empty array or record as suboptimal, just because a GitHub project can't return a preview image.

**Comment by jaredkerim** [comment]
@pdehaan Activity Stream is currently designed to omit highlights for which there is not a suitable preview image (below a certain size).  The current design of finding any image on the page and faking its size forces Activity Stream to show a highlight with a blown up icon as its preview, which is what we don't want.  By omitting the images field altogether, Activity Stream will prioritize pages with rich preview images so we don't wind up showing blown up icons.
