### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/page-metadata-service#68]
Error: Encoding not recognized: '''' (searched as: '')
    at Object.getCodec (/app/node_modules/iconv-lite/lib/index.js:102:23)
    at Object.getDecoder (/app/node_modules/iconv-lite/lib/index.js:118:23)
    at Object.decode (/app/node_modules/iconv-lite/lib/index.js:36:25)
    at convertIconvLite (/app/node_modules/encoding/lib/encoding.js:91:26)
    at convert (/app/node_modules/encoding/lib/encoding.js:51:22)
    at Body._convert (/app/node_modules/node-fetch/lib/body.js:193:9)
    at PassThrough.<anonymous> (/app/node_modules/node-fetch/lib/body.js:126:17)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)

Found a ton of these in the server logs today.  What does it mean?  @pdehaan?

**Comment by pdehaan** [comment]
We're not logging/sampling any related URLs, are we?

I literally can't even. From `iconv-lite`, i'd almost wonder if this is favicon related, or body-parser maybe.
Let me try installing w/ npm2 and see if I can pinpoint who is consuming these rogue node modules.

Stand by.

**Comment by pdehaan** [comment]
Well, for iconv-lite, it looks like it could be potentially one of 3 places (`body-parser`, `fetch-mock`, or `isomorphic-fetch`):

```sh
$ npm ls iconv-lite

page-metadata-service@0.1.0 /Users/pdehaan/dev/github/mozilla/page-metadata-service/app
├─┬ body-parser@1.15.2
│ └── iconv-lite@0.4.13
│
├─┬ fetch-mock@5.1.1
│ └─┬ node-fetch@1.6.0
│   └─┬ encoding@0.1.12
│     └── iconv-lite@0.4.13
│
└─┬ isomorphic-fetch@2.2.1
  └─┬ node-fetch@1.6.0
    └─┬ encoding@0.1.12
      └── iconv-lite@0.4.13
```

But maybe see if we can increase logging levels on the service temporarily (since we're not in prod and only using it internally). My initial guess is that `body-parser` is choking on invalid or missing favicons, but I have no evidence [yet] to back that theory up.

**Comment by pdehaan** [comment]
Actually, the stack above seems to reference `node-fetch` > `encoding` > `iconv-lite`, so according to my `npm ls` above, it's _clearly_ coming from the `isomorphic-fetch` module, since that signature matches exactly:

```
page-metadata-service@0.1.0 /Users/pdehaan/dev/github/mozilla/page-metadata-service/app
└─┬ isomorphic-fetch@2.2.1
  └─┬ node-fetch@1.6.0
    └─┬ encoding@0.1.12
      └── iconv-lite@0.4.13
```

Looks like `isomorphic-fetch` is only used in one place:

```js
function getUrlMetadata(url) {
  return fetch(url)
    .then((res) => {
      if (res.status >= 200 && res.status < 300) {
        return res;
      } else {
        const error = new Error(res.statusText);
        error.res = res;
        throw error;
      }
    })
    .then((res) => res.text())
    .then((body) => getDocumentMetadata(url, domino.createWindow(body)))
    .catch((err) => {
      return {};
    });
}
```
&mdash; via [./app/metadata.js:44-60](https://github.com/mozilla/page-metadata-service/blob/9dc93dcc3ea033331f203f15d99ac1042f164b6b/app/metadata.js#L44-L60)

We're seeing an error, so I'd guess it's the `throw error` line, probably. Which means for some reason we're getting a status outside of 200-300. Not sure if that should be `< 400`.

Also, because my eyes looked at this, I find the `return {}` in the `catch(err) => {}` marginally concerning as it could be swallowing errors. Not sure if we should be re-throwing an error, or at least returning the error string. Or sending everything through sentry for tracking of why we'd hit that `catch()` block.

**Comment by pdehaan** [comment]
Also, do we have Sentry set up on the server yet, or do we need to redeploy to pick up latest changes in master?
